let transactions=[],currentView="all",isAdmin=false,liveMode=false;
const money=v=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(v);
const normalizeDate=v=>{if(!v)return "";const s=String(v);if(/^\d{4}-\d{2}-\d{2}$/.test(s))return s;const d=new Date(s);return Number.isNaN(d.getTime())?s:d.toISOString().slice(0,10)};
const formatDate=v=>{const d=new Date(normalizeDate(v)+"T00:00:00");return Number.isNaN(d.getTime())?String(v):d.toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"})};
const $=id=>document.getElementById(id);
const els={incomeTotal:$("incomeTotal"),expenseTotal:$("expenseTotal"),balanceTotal:$("balanceTotal"),viewTitle:$("viewTitle"),body:$("transactionBody"),empty:$("emptyState"),count:$("entryCount"),panelIncome:$("panelIncome"),panelExpense:$("panelExpense"),panelNet:$("panelNet"),from:$("fromDate"),to:$("toDate"),adminButton:$("adminButton"),adminButtonText:$("adminButtonText"),backdrop:$("modalBackdrop"),content:$("modalContent")};
function totals(list){const income=list.filter(x=>x.type==="income").reduce((s,x)=>s+x.amount,0),expense=list.filter(x=>x.type==="expense").reduce((s,x)=>s+x.amount,0);return{income,expense,balance:income-expense}}
function filtered(){const from=els.from.value,to=els.to.value;return[...transactions].filter(x=>currentView==="all"||x.type===currentView).filter(x=>(!from||x.date>=from)&&(!to||x.date<=to)).sort((a,b)=>b.date.localeCompare(a.date)||b.id-a.id)}
function esc(v){return String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function render(){const list=filtered(),t=totals(list);els.viewTitle.textContent=currentView==="income"?"Income Transactions":currentView==="expense"?"Expenditure Transactions":"Total Aggregation";els.count.textContent=list.length;els.panelIncome.textContent=money(t.income);els.panelExpense.textContent=money(t.expense);els.panelNet.textContent=money(t.balance);els.body.innerHTML="";const chronological=[...transactions].sort((a,b)=>a.date.localeCompare(b.date)||a.id-b.id);let run=0,map=new Map;chronological.forEach(x=>{run+=x.type==="income"?x.amount:-x.amount;map.set(x.id,run)});list.forEach(x=>{const tr=document.createElement("tr");tr.innerHTML=`<td>${formatDate(x.date)}</td><td><span class="type-pill ${x.type==="income"?"type-income":"type-expense"}">${x.type==="income"?"Income":"Expenditure"}</span></td><td><strong>${esc(x.description)}</strong></td><td>${esc(x.category)}</td><td>${esc(x.payment)}</td><td class="amount ${x.type==="income"?"text-income":"text-expense"}">${x.type==="income"?"+":"-"} ${money(x.amount)}</td><td class="balance-col balance-positive">${money(map.get(x.id))}</td>`;els.body.appendChild(tr)});els.empty.hidden=list.length!==0;const all=totals(transactions);els.incomeTotal.textContent=money(all.income);els.expenseTotal.textContent=money(all.expense);els.balanceTotal.textContent=money(all.balance)}
function loadLiveData(){const url=window.APP_CONFIG&&window.APP_CONFIG.APPS_SCRIPT_URL;if(!url){showLoadError();return}const callback="templeFinanceCallback_"+Date.now();window[callback]=payload=>{try{if(payload&&Array.isArray(payload.transactions)){transactions=payload.transactions.map(x=>({...x,id:Number(x.id)||0,date:normalizeDate(x.date),type:String(x.type||"").toLowerCase(),description:String(x.description||""),category:String(x.category||""),payment:String(x.payment||""),amount:Number(x.amount)||0}));liveMode=true;render()}}finally{delete window[callback];script.remove()}};const script=document.createElement("script");script.src=url+(url.includes("?")?"&":"?")+"prefix="+encodeURIComponent(callback)+"&_="+Date.now();script.onerror=()=>{showLoadError();delete window[callback];script.remove()};document.head.appendChild(script)}
function showLoadError(){transactions=[];render();els.empty.hidden=false;els.empty.innerHTML="<div class=\"empty-icon\">!</div><h3>Finance data could not be loaded</h3><p>Please refresh the page and try again.</p>"}
els.adminButton.onclick=()=>{const target=window.APP_CONFIG&&window.APP_CONFIG.ADMIN_APP_URL;if(target)window.open(target,"_blank","noopener");else alert("Admin portal is not configured yet.")};
document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>{currentView=b.dataset.view;render();document.querySelector(".toolbar").scrollIntoView({behavior:"smooth",block:"start"})});
els.from.onchange=render;els.to.onchange=render;$("clearFilters").onclick=()=>{els.from.value="";els.to.value="";render()};els.backdrop.onclick=e=>{if(e.target===els.backdrop)els.backdrop.hidden=true};$("modalClose").onclick=()=>els.backdrop.hidden=true;render();loadLiveData();
